export type User = {
  id: string;
  name: string;
  email: string;
  password: string;
  roles: string[];
  active: boolean;
  avatar: string;
  cloudinary_url: string;
  createdAt: string;
  bday: number;
  gender: string;
  civilStatus: string;
  fathersName: string;
  mothersName: string;
  ethnicity: string;
  religion: string;
  nationality: string;
  address: string;
  workplace: string;
};
